name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python -c "import main"
        env:
          SECRET_KEY: 55ed149439caa95ebce4b36e824b84e1cf562ffd50630fb74ef6c4cd84223887
          DB_HOST: localhost
          DB_USER: myuser
          DB_PASSWORD: mypassword
          DB_NAME: mydb
